# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: linux-64
name: covid19-seir
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.1.3
  - python=3.6.13
  - scipy=1.5.2
  - us=1.0.0
  - pyspark=3.1.1